### ISSUE TITLE
TS2307: Cannot find module './App.svelte' or its corresponding type declarations.

### ISSUE THREAD

**Issue by lucrbvi** [baileyherbert/svelte-webpack-starter#14]
I just freshly install the template but when I do `npm run dev` I got an error message from WebPack that said that it cannot find `./App.svelte` but the file existe in the correct directory as the same level as `main.ts`... I just don't understand how to fix this...

**Comment by baileyherbert** [comment]
It seems to be stemming from the latest `typescript` version. You can run the following to get it working again:

```
npm install typescript@5.5.4
```

I'll look into the proper solution so we can continue to upgrade typescript.

**Comment by baileyherbert** [comment]
Fixed in ad4c5f749b757df6653f4f50f406b94d3ad2fe89. Needed to add a type reference to the `svelte` package.

If you're still interested in using this template, I recommend pulling a fresh copy, as the dependencies were updated to address a security vulnerability, and the webpack configuration file was updated for typescript 5.6.
